from typing import Literal  # Added Literal for status types

from pydantic import BaseModel, ConfigDict, Field

# Define a type for the status of an LLM analysis to make it explicit
LLMAnalysisStatus = Literal["success", "deferred_admin_notified", "critical_error_no_check"]

class LLMSpamAnalysisResult(BaseModel):
    """Result of an LLM spam analysis for a single message."""
    is_spam: bool | None = None # True if spam, False if not, None if check was deferred/failed critically
    reason: str | None = Field(None, max_length=100, description="Concise reason if spam, max 100 chars.")
    input_tokens: int | None = None # Number of input tokens used for the LLM call
    output_tokens: int | None = None # Number of output tokens generated by the LLM
    model_name_used: str | None = None # API identifier of the model that performed the check
    status: LLMAnalysisStatus = "success" # Overall status of the analysis attempt
    error_message: str | None = None # Detailed error if status is not 'success'

    model_config = ConfigDict(
        protected_namespaces=() # Allow field names like "model_*"
    )

class MessageContext(BaseModel):
    """Contextual information about a message being processed."""
    # This is stored in the queue when checks fail/are deferred.
    user_id: int
    chat_id: int
    message_id: int
    message_text: str
    sender_username: str | None = None
    sender_first_name: str | None = None
    is_new_user: bool = False # Usually True when queued, indicates if user was in NewUser table at time of message

class BanDetails(BaseModel):
    """Details required to perform a user ban action."""
    user_id: int
    chat_id: int
    reason: str # Internal reason for the ban (logged)
    delete_message_ids: list[int] = Field(default_factory=list) # Specific message IDs to delete upon ban
    notify_user_reason: str | None = None # Public reason sent to the chat before banning (if enabled)
